URL_SERVICE = "https://cnt-c18a8e9d-939e-4282-842c-a5a1c58685e1.containerhub.tripleten-services.com"
CREATE_USER_PATH = "/api/v1/users"
KITS_PATH = "/api/v1/kits"
PRODUCTS_KITS_PATH = "/api/v1/products/kits/"
LOG_MAIN_PATH = "/api/logs/main"
USER_TABLE_PATH = "/api/db/resources/product_model.csv"
